name: Build

on:
  push:
    branches: ["dev"]

jobs:
  test-build:
    runs-on: ubuntu-latest
    env:
      STORAGE_HOST: "127.0.0.1"
      STORAGE_PORT: "54321"
      STORAGE_PROTOCOL: "http"

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests and linter
        run: npm run lint && npm run build

      - name: Fail on failed tests
        run: |
          if [ ${{ job.status }} == 'failure' ]; then exit 1; fi;
